### ISSUE TITLE
ImportError: No module named 'four_corner_method'

### ISSUE THREAD

**Issue by ucaswxk** [howl-anderson/hanzi_char_featurizer#1]
ImportError: No module named 'four_corner_method'

**Comment by liuhe6** [comment]
同样的问题，请问是如何解决的？

**Comment by howl-anderson** [comment]
@liuhe6 能提供复现这一问题的最小代码么，方便我测试和修复。

**Comment by liuhe6** [comment]
clone下来之后，在setup.py的同级目录下创建了一个test.py文件 其中内容是
`
from hanzi_char_featurizer import Featurizor

featurizor = Featurizor()
result = featurizor.featurize('明天')
print(result)
`
然后就出现了上述问题

**Comment by howl-anderson** [comment]
我已经更新了代码，解决了依赖问题。
