### ISSUE TITLE
ImportError: No module named 'four_corner_method'

### ISSUE THREAD

**Issue by ytianjao** [howl-anderson/hanzi_char_featurizer#2]
hanzi_char_featurizer/featurizers/four_corner.py的错误
包里并没有four_corner_method'这个文件啊

**Comment by VincentKan** [comment]
ModuleNotFoundError: No module named 'four_corner_method'
我也遇到这个问题了

**Comment by VincentKan** [comment]
可以在博主的这个链接里找到https://github.com/howl-anderson/four_corner_method

**Comment by ytianjao** [comment]
多谢！

**Comment by howl-anderson** [comment]
我已经更新了代码，解决了依赖问题。
